// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgdWfxTMdFS0BB5jwh42FEf0h2jSH7jhk',
    appId: '1:866219640103:web:337a177b289bf3660a9502',
    messagingSenderId: '866219640103',
    projectId: 'fieldapp-a7447',
    authDomain: 'fieldapp-a7447.firebaseapp.com',
    databaseURL: 'https://fieldapp-a7447-default-rtdb.firebaseio.com',
    storageBucket: 'fieldapp-a7447.appspot.com',
    measurementId: 'G-3VR5ZNEP5C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDteDRP-1JbaTMyI4vDyeOw4bC8HEcw9tg',
    appId: '1:866219640103:android:6655f6f7169d13490a9502',
    messagingSenderId: '866219640103',
    projectId: 'fieldapp-a7447',
    databaseURL: 'https://fieldapp-a7447-default-rtdb.firebaseio.com',
    storageBucket: 'fieldapp-a7447.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8ny6hYYm7ycln62CdllYFYx8HLwsDgis',
    appId: '1:866219640103:ios:4f7bc8ffb4bb6e070a9502',
    messagingSenderId: '866219640103',
    projectId: 'fieldapp-a7447',
    databaseURL: 'https://fieldapp-a7447-default-rtdb.firebaseio.com',
    storageBucket: 'fieldapp-a7447.appspot.com',
    androidClientId: '866219640103-0on1k0jbc6k8rf5tmaohltf5sr3pkpth.apps.googleusercontent.com',
    iosClientId: '866219640103-1l8rgj1ro7r6ejcflg4ku9ngqvd1p3a7.apps.googleusercontent.com',
    iosBundleId: 'com.example.fieldappRcm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8ny6hYYm7ycln62CdllYFYx8HLwsDgis',
    appId: '1:866219640103:ios:0bf039ec5022d6f90a9502',
    messagingSenderId: '866219640103',
    projectId: 'fieldapp-a7447',
    databaseURL: 'https://fieldapp-a7447-default-rtdb.firebaseio.com',
    storageBucket: 'fieldapp-a7447.appspot.com',
    androidClientId: '866219640103-0on1k0jbc6k8rf5tmaohltf5sr3pkpth.apps.googleusercontent.com',
    iosClientId: '866219640103-shts4134hgmbving6dt4lbs4217cvnt5.apps.googleusercontent.com',
    iosBundleId: 'com.example.fieldappRcm.RunnerTests',
  );
}
